config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    resources :syn_data_requests
  end

  root 'pages#home'

  get '/about' => 'pages#about'
  get '/prism_evaluation' => 'pages#prism_evaluation'
  get '/prism_dashboard' => 'pages#prism_dashboard'
  get '/our_methods' => 'pages#our_methods'
  get '/requests/new' => 'syn_data_requests#new'
  get 'user/requests' => 'syn_data_requests#index'
  get 'user/requests/show' => 'syn_data_requests#show'

  get '/get_data' => 'prism#get_data'
  get '/get_data_500' => 'prism#get_data_500'
  get '/get_data_1000' => 'prism#get_data_1000'
  post '/filter_data' => 'prism#filter_data'

  get '/get_tSNE_data' => 'eval#get_tSNE_data'
  get '/get_PCA_data' => 'eval#get_PCA_data'
  get '/get_tPred_data' => 'eval#get_tPred_data'
  get '/get_MSE3_data' => 'eval#get_MSE3_data'
  get '/get_cat_data' => 'eval#get_cat_data'
  get '/get_num_data' => 'eval#get_num_data'
  get '/get_num_data_5000' => 'eval#get_num_data_5000'
  get '/get_MSE1_data' => 'eval#get_MSE1_data'
  get '/get_auto_visit_data' => 'eval#get_auto_visit_data'
  get '/get_auto_malaria_data' => 'eval#get_auto_malaria_data'

  devise_scope :user do
    get '/sign-in' => "devise/sessions#new", :as => :login
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/autocorrelation_malarium.rb
class AutocorrelationMalarium < ApplicationRecord
end

app/models/autocorrelation_visitweek.rb
class AutocorrelationVisitweek < ApplicationRecord
end

app/models/mse12_coordinate.rb
class Mse12Coordinate < ApplicationRecord
end

app/models/mse13_coordinate.rb
class Mse13Coordinate < ApplicationRecord
end

app/models/mse1_coordinate.rb
class Mse1Coordinate < ApplicationRecord
end

app/models/mse3_coordinate.rb
class Mse3Coordinate < ApplicationRecord
end

app/models/pca_coordinate.rb
class PcaCoordinate < ApplicationRecord
end

app/models/prism_observation.rb
class PrismObservation < ApplicationRecord
    self.per_page = 20
end

app/models/syn_data_request.rb
class SynDataRequest < ApplicationRecord
  belongs_to :user
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :company_name, presence: true
  validates :dataset_name, presence: true
  validates :dataset_type, presence: true
end

app/models/t_predictive_coordinate.rb
class TPredictiveCoordinate < ApplicationRecord
end

app/models/t_sne.rb
class TSne < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :syn_data_requests, dependent: :destroy
end

app/controllers/eval_controller.rb
class EvalController < ApplicationController

    protect_from_forgery with: :null_session
    respond_to :js, :json, :html

    def get_tSNE_data
        @tSNE_data = TSne.all.to_json()
        render json: @tSNE_data
    end

    def get_PCA_data
        @PCA_data = PcaCoordinate.all.to_json()
        render json: @PCA_data
    end

    def get_tPred_data
        @tPred_data = TPredictiveCoordinate.all.to_json()
        render json: @tPred_data
    end

    def get_MSE3_data
        @MSE3_data = Mse3Coordinate.all.to_json()
        render json: @MSE3_data
    end

    def get_cat_data
        @cat_data = DistributionCatCoordinate.all.to_json()
        render json: @cat_data
    end

    def get_num_data
        @num_data = DistributionNumCoordinatesToday.all.to_json()
        render json: @num_data
    end

    def get_num_data_5000
      @num_data = DistributionNumCoordinatesToday.first(5000).to_json()
      render json: @num_data
    end

    def get_MSE1_data
        @MSE1_data = Mse13Coordinate.all.to_json()
        render json: @MSE1_data
    end

    def get_auto_visit_data
        @auto_visit_data = AutocorrelationVisitweek.all.to_json()
        render json: @auto_visit_data
    end

    def get_auto_malaria_data
        @auto_malaria_data = AutocorrelationMalarium.all.to_json()
        render json: @auto_malaria_data
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @observations = PrismObservation.paginate(page: params[:page])
    @prism_dataset = PrismObservation.first(1000).to_json
  end

  def about
  end

  def our_methods
  end

  def prism_dashboard
  end

  def prism_evaluation
  end

end

app/controllers/prism_controller.rb
class PrismController < ApplicationController

  protect_from_forgery with: :null_session
  respond_to :js, :json, :html

  def get_data
    @prism_data = PrismObservation.all.to_json()
    render json: @prism_data
  end

  def filter_data
    column = params[:column]
    start = params[:filter]['0']['value']
    final = params[:filter]['1']['value']

    @filtered = PrismObservation.where(column => start..final)
    render json: @filtered
  end

  def get_data_500
    @prism_data = PrismObservation.first(500).to_json()
    render json: @prism_data
  end

  def get_data_1000
    @prism_data = PrismObservation.first(1000).to_json()
    render json: @prism_data
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def replace_na(variable)
        if variable.is_a?(NilClass) 
            return "N/A" 
        else 
            return variable
        end
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prism_helper.rb
module PrismHelper
end

app/helpers/syn_data_requests_helper.rb
module SynDataRequestsHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small pt-4 scheme" id="sticky-footer">
  <div class="container-fluid text-center text-md-left">
    <div class="row">
      <div class="col-md-6 mt-md-0 mt-3">
        <h5 class="text-uppercase">Syndasera</h5>
        <p>The synthetic data service was a tool designed by the 2020 Health Data Insight intern
        team: Aisha, Evonne, Faiz, Harry, Lulu, and Rebeca. To read more about the project, 
        <a href="/about">click here</a>.</p>
      </div>
      <hr class="clearfix w-100 d-md-none pb-3">
      <div class="col-md-3 mb-md-0 mb-3">
        <h5 class="text-uppercase">Quick Links</h5>
        <ul class="list-unstyled">
          <li>
            <a href="https://clinepidb.org/ce/app/record/dataset/DS_0ad509829e">
                PRISM dataset
            </a>
          </li>
          <li>
            <a href="https://www.gov.uk/government/organisations/public-health-england">
            PHE Website
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-3 mb-md-0 mb-3">
        <h5 class="text-uppercase">Contact Us</h5>
        <ul class="list-unstyled">
          <li>
            <a href="https://twitter.com/hdi_cambridge" 
        class="twitter-follow-button" data-show-count="false">
        Follow @HDI</a><script async src="https://platform.twitter.com/widgets.js" 
        charset="utf-8"></script>
          </li>
          <li>
            <a href="mailto:admin@healthdatainsight.org.uk">Send us an email!</a> 
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="footer-copyright text-center py-3" style="background-color: #b9dbdf;">
    <small>Copyright &copy; 2020 
        <a href="https://healthdatainsight.org.uk/">
            <b>Health Data Insight</b>
        </a>
    </small>
  </div>

</footer>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/navbar_user' %>
<% else %>
  <%= render 'layouts/navbar_guest' %>
<% end %>

app/views/layouts/_navbar_guest.html.erb
<nav class="navbar navbar-expand-lg navbar-light scheme">
  <a class="navbar-brand" href="/">
    <%= image_tag("eye_logo.png", :alt => "logo", :size => "64x44") %>
    <span class="logo">Syndasera</span>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
        <a class="nav-link" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item <%= 'active' if current_page?(about_path) %>">
        <a class="nav-link" href="<%= about_path %>">About</a>
      </li>
      <li class="nav-item <%= 'active' if current_page?(requests_new_path) %>">
        <a class="nav-link" href="<%= requests_new_path %>">Make A Request</a>
      </li>
      <li class="nav-item <%= 'active' if current_page?(our_methods_path) %>">
        <a class="nav-link" href="<%= our_methods_path %>">Our Methods</a>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li>
        <div class="btn-nav">
            <%= link_to('Sign Up', new_user_registration_path, :class => "btn btn-secondary") %>
        </div>
      </li>
      <li>
        <div class="btn-nav">
            <%= link_to('Log In', new_user_session_path, :class => "btn btn-secondary") %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_navbar_user.html.erb
<nav class="navbar navbar-expand-lg navbar-light scheme">
  <a class="navbar-brand" href="/">
    <%= image_tag("eye_logo.png", :alt => "logo", :size => "64x44") %>
    <span class="logo">Syndasera</span>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" 
    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
        <a class="nav-link" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item <%= 'active' if current_page?(about_path) %>">
        <a class="nav-link" href="<%= about_path %>">About</a>
      </li>
      <li class="nav-item <%= 'active' if current_page?(requests_new_path) %>">
        <a class="nav-link" href="<%= requests_new_path %>">Make A Request</a>
      </li>
      <li class="nav-item <%= 'active' if current_page?(our_methods_path) %>">
        <a class="nav-link" href="<%= our_methods_path %>">Our Methods</a>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <button class="dropdown-toggle btn-nav btn btn-secondary" data-toggle="dropdown" id="dp"
          role="button" aria-haspopup="true" aria-expanded="false" type="button">
          <%= current_user.email %>
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dp">
          <li class="dropdown-items">
            <%= link_to('My Requests', user_syn_data_requests_path(current_user), :class => "link-to") %>
          </li>
          <div class="dropdown-divider"></div>
          <li class="dropdown-items">
            <%= link_to('Edit Profile', edit_user_registration_path, :class => "link-to") %>
          </li>
          <div class="dropdown-divider"></div>
          <li class="dropdown-items">
            <%= link_to('Log Out', destroy_user_session_path, 
              :method => :delete, :class => "link-to") %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Syndasera</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>

    <%= render 'layouts/navbar' %>
  </head>

  <body>
    <div class='container body-container'>
      <%= yield %>
    </div>
    <br>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_filter_forms.html.erb
<div class="container number filter-div">
	<div class="row">
		<div class="col-sm-8">
			<h3>Filter by <span class="number-id">Age</span></h3>
		</div>
	</div>
	<hr>

	<form class="number-form filter-form">
		<div class="form-row">
			<div class="form-group col-md-3">
				<label for="num-from">Select from</label>
				<input type="number" class="form-control" id="num-from" name="number-start" placeholder="0">
			</div>

			<div class="form-group col-md-3">
				<label for="num-to">to</label>
				<input type="number" class="form-control" id="num-to" name="number-end" placeholder="100">
			</div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-3">
				<div class="form-check">
					<label class="form-check-label checkbox-inline" for="null-values">
						<input class="form-check-input" type="checkbox" value="" id="null-values">
						Include null values
					</label>
				</div>
				<br>
				<button type="button" class="btn btn-success go-filter-button" id="number-form" name="number">Go</button>
			</div>
		</div>
	</form>
</div>

<div class="container date filter-div">
	<div class="row">
		<div class="col-sm-8">
			<h3>Filter by <span class="date-id"></span></h3>
		</div>
	</div>

	<hr>

	<form class="date-form filter-form">
		<div class="form-row">
			<div class="form-group col-md-4">
				<label for="date-from">Start Date</label>
				<input type="date" class="form-control" id="date-from" name="date-start" placeholder="0">
			</div>
			<div class="form-group col-md-4">
				<label for="date-to">End Date</label>
				<input type="date" class="form-control" id="date-to" name="date-end" placeholder="100">
			</div>
		</div>
		<button type="button" class="btn btn-success go-filter-button" id="date-form" name='date'>Go</button>
	</form>
</div>

app/views/pages/_table.html.erb
<table class="table table-striped table-bordered">
	<thead>
    <tr class="header-row">
			<th>Participant ID</th>
			<th>Household ID</th>
			<th>Visit Date</th>
			<th>Age</th>
			<th>Weight (kg)</th>
			<th>Temperature (C)</th>
			<th>Abdominal Pain Duration</th>
			<th>Admitting Hospital</th>
			<th>Anorexia Duration</th>
			<th>Plasmodium Parasite Density</th>
			<th>Basis of Complicated Diagnosis</th>
			<th>Complicated Malaria</th>
			<th>Cough Duration</th>
			<th>Diagnosis at Hospitalisation</th>
			<th>Diarrhoea Duration</th>
			<th>Fatigue Duration</th>
			<th>Fever Duration</th>
			<th>Headache Duration</th>
			<th>Hospital Admission Date</th>
			<th>Hospital Discharge Date</th>
			<th>ITN Last Night</th>
			<th>Jaundice Duration</th>
			<th>Joint Pains Duration</th>
			<th>Malaria Diagnosis</th>
			<th>Malaria Diagnosis and Parasite Status</th>
			<th>Malaria Treatment</th>
			<th>Muscle Aches Duration</th>
			<th>Non Malaria Medication</th>
			<th>Other Diagnosis</th>
			<th>Other Medical Complaint</th>
			<th>Plasmodium Gametocytes Present</th>
			<th>Seizures Duration</th>
			<th>Severe Malaria Criteria</th>
			<th>Subjective Fever</th>
			<th>Submicroscopic Plasmodium Present</th>
			<th>Visit Type</th>
			<th>Vomiting Duration</th>
    </tr>
	</thead>

	<div class="table-body">
		<% @observations.each do |observation| %>
			<tr class="data-row">
				<td class="participant-id">
					<%= replace_na(observation.participant_id) %>
				</td>
				<td class="col household-id">
					<%= replace_na(observation.household_id) %>
				</td>
				<td class="col visit-date nowrap">
					<%= replace_na(observation.visit_date) %>
				</td>
				<td class="col age">
					<%= replace_na(observation.age) %>
				</td>
				<td class="col weight">
					<%= replace_na(observation.weight) %>
				</td>
				<td class="col temperature">
					<%= replace_na(observation.temperature) %>
				</td>
				<td class="col abdominal-pain-duration">
					<%= replace_na(observation.abdominal_pain_duration) %>
				</td>
				<td class="col admitting-hospital">
					<%= replace_na(observation.admitting_hospital) %>
				</td>
				<td class="col anorexia-duration">
					<%= replace_na(observation.anorexia_duration) %>
				</td>
				<td class="col plasmodium-parasite-density">
					<%= replace_na(observation.plasmodium_parasite_density) %>
				</td>
				<td class="col basis-of-complicated-diagnosis">
					<%= replace_na(observation.basis_of_complicated_diagnosis) %>
				</td>
				<td class="col complicated-malaria">
					<%= replace_na(observation.complicated_malaria) %>
				</td>
				<td class="col cough-duration">
					<%= replace_na(observation.cough_duration) %>
				</td>
				<td class="col diagnosis-at-hospitalisation">
					<%= replace_na(observation.diagnosis_at_hospitalisation) %>
				</td>
				<td class="col diarrhoea-duration">
					<%= replace_na(observation.diarrhoea_duration) %>
				</td>
				<td class="col fatigue-duration">
					<%= replace_na(observation.fatigue_duration) %>
				</td>
				<td class="col fever-duration">
					<%= replace_na(observation.fever_duration) %>
				</td>
				<td class="col headache-duration">
					<%= replace_na(observation.headache_duration) %>
				</td>
				<td class="col hospital-admission-date nowrap">
					<%= replace_na(observation.hospital_admission_date) %>
				</td>
				<td class="col hospital-discharge-date nowrap">
					<%= replace_na(observation.hospital_discharge_date) %>
				</td>
				<td class="col itn-last-night">
					<%= replace_na(observation.itn_last_night) %>
				</td>
				<td class="col jaundice-duration">
					<%= replace_na(observation.jaundice_duration) %>
				</td>
				<td class="col joint-pains-duration">
					<%= replace_na(observation.joint_pains_duration) %>
				</td>
				<td class="col malaria-diagnosis">
					<%= replace_na(observation.malaria_diagnosis) %>
				</td>
				<td class="col malaria-diagnosis-and-parasite-status nowrap">
					<%= replace_na(observation.malaria_diagnosis_and_parasite_status) %>
				</td>
				<td class="col malaria-treatment">
					<%= replace_na(observation.malaria_treatment) %>
				</td>
				<td class="col muscle-aches-duration">
					<%= replace_na(observation.muscle_aches_duration) %>
				</td>
				<td class="col non-malaria-medication">
					<%= replace_na(observation.non_malaria_medication) %>
				</td>
				<td class="col other-diagnosis">
					<%= replace_na(observation.other_diagnosis) %>
				</td>
				<td class="col other-medical-complaint">
					<%= replace_na(observation.other_medical_complaint) %>
				</td>
				<td class="col plasmodium-gametocytes-present">
					<%= replace_na(observation.plasmodium_gametocytes_present) %>
				</td>
				<td class="col seizures-duration">
					<%= replace_na(observation.seizures_duration) %>
				</td>
				<td class="col severe-malaria-criteria">
					<%= replace_na(observation.severe_malaria_criteria) %>
				</td>
				<td class="col subjective-fever">
					<%= replace_na(observation.subjective_fever) %>
				</td>
				<td class="col submicroscopic-plasmodium-present">
					<%= replace_na(observation.submicroscopic_plasmodium_present) %>
				</td>
				<td class="col visit-type">
					<%= replace_na(observation.visit_type) %>
				</td>
				<td class="col vomiting-duration">
					<%= replace_na(observation.vomiting_duration) %>
				</td>
			</tr>
		<% end %>
	</div>
</table>

app/views/pages/about.html.erb
<h3>What is Syndasera?</h3>

<p>
The synthetic data service, aka Syndasera, is a tool designed by the 2020 Health Data Insight
(HDI) intern team: 
Aisha, Evonne, Faiz, Harry, Lulu, and Rebeca. It involved three main branches of design:

<ul>
	<li>
		AI Algorithms were used to generate the synthetic data itself using multiple advanced machine
		learning models such as Generative Adversarial Networks to train on the datasets supplied.
	</li>
	<li>
		Privacy & Evaluation methods were implemented to ensure that the data generated was in fact
		realistic compared to the original dataset and fully anonymised.
	</li>
	<li>
		Web Development included developing this website, handling backend requests for synthetic
		data and visualisations, and setting up the Dataset Access Environment where users can
		safetly upload their data.
	</li>
</ul>

<p>
HDI is a social enterprise overseen by the Office of the Regulator of Community Interest Companies 
which ensures we meet our social purpose and that the value we create is protected and used for 
social good.
</p>
<%= image_tag("hdi_banner.png", :alt => "HDI", :height => "250", :class => "banner") %>
<br>

<p>Our aims are to:</p>
<ul>
	<li>
		create value for public sector organisations by finding new knowledge from both existing and new
		sources of information
	</li>
	<li>
		provide a data management and linkage service that allows partners to access information
		in safe-havens that guarantee the privacy of each individual patient.
	</li>
	<li>
		create visual, internet-based information services and applications that can be easily accessed,
		used and understood
	</li>
	<li>
		supply organisations with information and services that they can use to understand and help
		improve their services</li>
	<li>
		deliver information to patients in accessible ways to help them improve the ways they choose, 
		access and use services and understand their clinical condition and care.
	</li>
</ul>


<p>
Our strategic objectives are aligned to NHS and wider government policy to improve transparency and
access to data, encourage self-management, enable choice and foster the use of social enterprises to 
deliver public services.
</p>

<p>
Our aims are aligned to NHS and wider government policy to improve transparency and access to data, 
encourage self-management, enable choice and foster the use of social enterprises to deliver public
services.
</p>

<p>
HDI conducts all its activities openly and transparently and is held to account through its annual
report to The Office of the Regulator of Community Interest Companies on what it has delivered for
its approved communities.
</p>

app/views/pages/home.html.erb
<h3>Project Summary</h3>

Syndasera is a dynamic synthetic data service allowing users like yourselves to create requests
for synthetic data generation from a real time-series patient dataset. We use sophisticated machine
learning algorithms and effective privacy evaluations to make sure that your synthesised data is as
realistic as possible whist protecting the privacy of your patients, which is of utmost importance.
Please see below for an example of data synthesised from the
<a target="_blank" href="https://clinepidb.org/ce/app/record/dataset/DS_0ad509829e">
  <span data-toggle="tooltip" style="font-weight:bold;" data-placement="right"
        title="PRISM was a longitudinal cohort study conducted in different transmission settings in Uganda.
        All children 6 months to 10 years old within a household and up to one primary caregiver were
        enrolled in a dynamic cohort, and children were excluded from follow-up after reaching 11 years of age.
        Participants had routine clinic visits roughly every 3 months and attended a study clinic any
        time they became ill.">
Program for Resistance, Immunology, Surveillance and Modeling of Malaria (PRISM) dataset.
</span></a>

<hr>
<%= javascript_include_tag 'home.js' %>

<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-header text-center">
        <b>Subset by Column</b>
        <br>
        <button class="btn btn-info" type="button" id="select-all">Select All</button>
        <button class="btn btn-info" type="button" id="select-none">Select None</button>
      </div>
      <div class="list-group subset-group">
        <!-- rendered from home.js with jquery-->
      </div>
    </div>
  </div>

  <div class="col-md-8 filter">
    <!-- rendered from home.js with jquery -->
    <%= render 'pages/filter_forms' %>
  </div>
</div>

<br>


<div class="loading">
  <br>
  <div class="text-center">
    <b>Loading Filtered Graphs</b>
    <div class="spinner-border text-info" role="status"></div>
  </div>
</div>
<!-- rendered from home.js with d3 -->


<div id="dashboard" class="text-center">
  <%= image_tag "loader.gif", id:"loader", class:"loader-img" %>
  <button type="button" class="btn btn-info graph-display">Show Graphs</button>
</div>
<%= javascript_include_tag 'prism-dashboard.js' %>

<div id="content"></div>

<div class="notes col-md-12 text-muted">
  <p>*Graphs drawn on 1000 rows for performance</p>
</div>

<div class="data-table">
  <%= render 'pages/table' %>
</div>

<br>
<div class="text-center pagination-div">
  <div class="page_info">
    <%= page_entries_info @observations %>
  </div>
  <%= will_paginate @observations, :container => false,
  renderer: WillPaginate::ActionView::BootstrapLinkRenderer,
  list_classes: %w(pagination justify-content-center) %>
  <div class="notes col-md-12 text-muted">
    <p>*All durations are in days, all dates are in the form YYYY/MM/DD, all weights are in kg,
    and all temperatures are measured in &#8451;</p>
  </div>
</div>

app/views/pages/make_request.html.erb
<div class="logsignin">
	<h2>Make a Request</h2>
	<p>Make a request to generate synthetic data from a proposed dataset.</p>

	<div class="form-container col-md-12">
		
	</div>
</div>

app/views/pages/prism_dashboard.html.erb
<%= javascript_include_tag 'prism-dashboard.js' %>
<div id="content"></div>
<div id="dashboard" class="text-center"></div>

app/views/pages/prism_evaluation.erb
<%= javascript_include_tag 'PRISM-evaluation.js' %>